=== LFMH/mapping-private/xml_to_semantic_map/test/SemanticMap.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
DTD for the Semantic Object Map
-->

<!ELEMENT SemanticMap	(wall | knob | candidate | handle)+>

<!ELEMENT wall      (model, minD, maxD)>
  <!ATTLIST wall name CDATA #REQUIRED>
  <!ATTLIST wall id CDATA #REQUIRED>

<!ELEMENT knob      (center, radius, doorID)>
  <!ATTLIST knob name CDATA #REQUIRED>
  <!ATTLIST knob id CDATA #REQUIRED>

<!ELEMENT handle    (center, elongation, doorID)>
  <!ATTLIST handle name CDATA #REQUIRED>
  <!ATTLIST handle id CDATA #REQUIRED>

<!ELEMENT candidate (wallID, face+, handles, knobs)>
  <!ATTLIST candidate name CDATA #REQUIRED>
  <!ATTLIST candidate typename CDATA #REQUIRED>
  <!ATTLIST candidate id CDATA #REQUIRED>
  <!ATTLIST candidate type CDATA #REQUIRED>

<!ELEMENT face (point0, point1, point2, point3)>
  <!ATTLIST face side CDATA #REQUIRED>

<!ELEMENT model      (#PCDATA)>
<!ELEMENT minD       (#PCDATA)>
<!ELEMENT maxD       (#PCDATA)>
<!ELEMENT center     (#PCDATA)>
<!ELEMENT radius     (#PCDATA)>
<!ELEMENT doorID     (#PCDATA)>
<!ELEMENT wallID     (#PCDATA)>
<!ELEMENT handles    (#PCDATA)>
<!ELEMENT knobs      (#PCDATA)>
<!ELEMENT elongation (#PCDATA)>
<!ELEMENT point0     (#PCDATA)>
<!ELEMENT point1     (#PCDATA)>
<!ELEMENT point2     (#PCDATA)>
<!ELEMENT point3     (#PCDATA)>

=== LFMH/mapping-private/xml_to_semantic_map/data/cad_based_map.xml
<?xml version="1.0"?>
<!DOCTYPE SemanticMap PUBLIC "" "SemanticMap.dtd">

<SemanticMap>
	<handle name="handle17000" id="17000">
		<center>0.292012 0.0285895 0.302548</center>
		<elongation>0.178959 0.00466835 0.00152457</elongation>
		<doorID>25000</doorID>
	</handle>

	<candidate name="cupboard0" id="25000" type="25000" typename="cupboard">
		<wallID>-1</wallID>
		<face side="front">
			<point0>-3.00753 0.574538 0.157324</point0>
			<point1>-3.00753 0.574538 0.495445</point1>
			<point2>-2.42708 0.574538 0.495445</point2>
			<point3>-2.42708 0.574538 0.157324</point3>
		</face>
		<face side="back">
			<point0>-3.01753 0.564538 0.147324</point0>
			<point1>-3.01753 0.564538 0.485445</point1>
			<point2>-2.43708 0.564538 0.485445</point2>
			<point3>-2.43708 0.564538 0.147324</point3>
		</face>
		<handles>17000 </handles>
		<knobs></knobs>
	</candidate>

	<handle name="handle17005" id="17005">
		<center>0.15 0.0376099 0.812527</center>
		<elongation>0.18 0.0061208 0.00278479</elongation>
		<doorID>25001</doorID>
	</handle>

	<candidate name="cupboard1" id="25001" type="25000" typename="cupboard">
		<wallID>-1</wallID>
		<face side="front">
			<point0>-0.37 0.574353 0.15795</point0>
			<point1>-0.37 0.574353 1.47362</point1>
			<point2>-0.0595746 0.574353 1.47362</point2>
			<point3>-0.0595746 0.574353 0.15795</point3>
		</face>
		<face side="back">
			<point0>-0.38 0.564353 0.14795</point0>
			<point1>-0.38 0.564353 1.46362</point1>
			<point2>-0.0695746 0.564353 1.46362</point2>
			<point3>-0.0695746 0.564353 0.14795</point3>
		</face>
		<handles>17005 </handles>
		<knobs></knobs>
	</candidate>

	<handle name="handle17008" id="17008">
		<center>0.146303 0.0306215 0.813734</center>
		<elongation>0.178605 0.00952679 0.00429827</elongation>
		<doorID>25002</doorID>
	</handle>

	<candidate name="cupboard2" id="25002" type="25000" typename="cupboard">
		<wallID>-1</wallID>
		<face side="front">
			<point0>0.533 0.572308 0.157378</point0>
			<point1>0.533 0.572308 1.47558</point1>
			<point2>0.822617 0.572308 1.47558</point2>
			<point3>0.822617 0.572308 0.157378</point3>
		</face>
		<face side="back">
			<point0>0.523 0.562308 0.147378</point0>
			<point1>0.523 0.562308 1.46558</point1>
			<point2>0.812617 0.562308 1.46558</point2>
			<point3>0.812617 0.562308 0.147378</point3>
		</face>
		<handles>17008 </handles>
		<knobs></knobs>
	</candidate>

	<handle name="handle17009" id="17009">
		<center>0.29 0.0251064 0.48857</center>
		<elongation>0.50899 0.0186943 0.00577462</elongation>
		<doorID>25003</doorID>
	</handle>

	<knob name="knob18000" id="18000">
		<center>0.035 0.0200414 0.57</center>
		<radius>0.015</radius>
		<doorID>25003</doorID>
	</knob>

	<knob name="knob18001" id="18001">
		<center>0.085 0.0200414 0.57</center>
		<radius>0.015</radius>
		<doorID>25003</doorID>
	</knob>

	<knob name="knob18002" id="18002">
		<center>0.125 0.0200414 0.57</center>
		<radius>0.015</radius>
		<doorID>25003</doorID>
	</knob>

	<knob name="knob18003" id="18003">
		<center>0.16 0.0200414 0.57</center>
		<radius>0.015</radius>
		<doorID>25003</doorID>
	</knob>

	<knob name="knob18004" id="18004">
		<center>0.2 0.0200414 0.57</center>
		<radius>0.015</radius>
		<doorID>25003</doorID>
	</knob>

	<knob name="knob18005" id="18005">
		<center>0.255 0.0200414 0.57</center>
		<radius>0.015</radius>
		<doorID>25003</doorID>
	</knob>

	<candidate name="cupboard3" id="25003" type="25000" typename="cupboard">
		<wallID>-1</wallID>
		<face side="front">
			<point0>-0.0565787 0.574795 0.86491</point0>
			<point1>-0.0565787 0.574795 1.47254</point1>
			<point2>0.517622 0.574795 1.47254</point2>
			<point3>0.517622 0.574795 0.86491</point3>
		</face>
		<face side="back">
			<point0>-0.0565787 0.564795 0.85491</point0>
			<point1>-0.0565787 0.564795 1.46254</point1>
			<point2>0.517622 0.564795 1.46254</point2>
			<point3>0.517622 0.564795 0.85491</point3>
		</face>
		<handles>17009 </handles>
		<knobs>18000 18001 18002 18003 18004 18005 </knobs>
	</candidate>

	<handle name="handle17007" id="17007">
		<center>0.28611 0.0330214 0.528294</center>
		<elongation>0.179062 0.00896072 0.00692618</elongation>
		<doorID>25004</doorID>
	</handle>

	<candidate name="cupboard4" id="25004" type="25000" typename="cupboard">
		<wallID>-1</wallID>
		<face side="front">
			<point0>-0.0565787 0.570865 0.159535</point0>
			<point1>-0.0565787 0.570865 0.727</point1>
			<point2>0.517622 0.570865 0.727</point2>
			<point3>0.517622 0.570865 0.159535</point3>
		</face>
		<face side="back">
			<point0>-0.0665787 0.560865 0.149535</point0>
			<point1>-0.0665787 0.560865 0.717</point1>
			<point2>0.507622 0.560865 0.717</point2>
			<point3>0.507622 0.560865 0.149535</point3>
		</face>
		<handles>17007 </handles>
		<knobs></knobs>
	</candidate>

	<handle name="handle17001" id="17001">
		<center>0.315961 0.0314454 0.565399</center>
		<elongation>0.18 0.00569415 0.000487447</elongation>
		<doorID>25005</doorID>
	</handle>

	<candidate name="cupboard5" id="25005" type="25000" typename="cupboard">
		<wallID>-1</wallID>
		<face side="front">
			<point0>-2.41096 0.780802 0.0694195</point0>
			<point1>-2.41096 0.780802 0.666611</point1>
			<point2>-1.798 0.780802 0.666611</point2>
			<point3>-1.798 0.780802 0.0694195</point3>
		</face>
		<face side="back">
			<point0>-2.42096 0.770802 0.0594194</point0>
			<point1>-2.42096 0.770802 0.656611</point1>
			<point2>-1.808 0.770802 0.656611</point2>
			<point3>-1.808 0.770802 0.0594194</point3>
		</face>
		<handles>17001 </handles>
		<knobs></knobs>
	</candidate>

	<handle name="handle17002" id="17002">
		<center>0.303 0.0324776 0.667366</center>
		<elongation>0.18 0.00787163 0.000819564</elongation>
		<doorID>25006</doorID>
	</handle>

	<candidate name="cupboard6" id="25006" type="25000" typename="cupboard">
		<wallID>-1</wallID>
		<face side="front">
			<point0>-1.798 0.780982 0.108349</point0>
			<point1>-1.798 0.780982 0.832126</point1>
			<point2>-1.20746 0.780982 0.832126</point2>
			<point3>-1.20746 0.780982 0.108349</point3>
		</face>
		<face side="back">
			<point0>-1.808 0.770982 0.0983487</point0>
			<point1>-1.808 0.770982 0.822126</point1>
			<point2>-1.21746 0.770982 0.822126</point2>
			<point3>-1.21746 0.770982 0.0983487</point3>
		</face>
		<handles>17002 </handles>
		<knobs></knobs>
	</candidate>

	<handle name="handle17003" id="17003">
		<center>0.386491 0.0292392 0.233343</center>
		<elongation>0.18 0.00522155 0.00308084</elongation>
		<doorID>25007</doorID>
	</handle>

	<candidate name="cupboard7" id="25007" type="25000" typename="cupboard">
		<wallID>-1</wallID>
		<face side="front">
			<point0>-1.18149 0.782271 0.109611</point0>
			<point1>-1.18149 0.782271 0.376848</point1>
			<point2>-0.396102 0.782271 0.376848</point2>
			<point3>-0.396102 0.782271 0.109611</point3>
		</face>
		<face side="back">
			<point0>-1.19149 0.772271 0.0996113</point0>
			<point1>-1.19149 0.772271 0.366848</point1>
			<point2>-0.406102 0.772271 0.366848</point2>
			<point3>-0.406102 0.772271 0.0996113</point3>
		</face>
		<handles>17003 </handles>
		<knobs></knobs>
	</candidate>

	<handle name="handle17004" id="17004">
		<center>0.386217 0.0301716 0.23429</center>
		<elongation>0.18 0.00448108 0.00418764</elongation>
		<doorID>25008</doorID>
	</handle>

	<candidate name="cupboard8" id="25008" type="25000" typename="cupboard">
		<wallID>-1</wallID>
		<face side="front">
			<point0>-1.18122 0.781565 0.397552</point0>
			<point1>-1.18122 0.781565 0.666847</point1>
			<point2>-0.395 0.781565 0.666847</point2>
			<point3>-0.395 0.781565 0.397552</point3>
		</face>
		<face side="back">
			<point0>-1.19122 0.771565 0.387552</point0>
			<point1>-1.19122 0.771565 0.656847</point1>
			<point2>-0.405 0.771565 0.656847</point2>
			<point3>-0.405 0.771565 0.387552</point3>
		</face>
		<handles>17004 </handles>
		<knobs></knobs>
	</candidate>

	<handle name="handle17006" id="17006">
		<center>0.386073 0.0192609 0.0892412</center>
		<elongation>0.18 0.00448751 0.0061506</elongation>
		<doorID>25009</doorID>
	</handle>

	<candidate name="cupboard9" id="25009" type="25000" typename="cupboard">
		<wallID>-1</wallID>
		<face side="front">
			<point0>-1.18107 0.782328 0.69128</point0>
			<point1>-1.18107 0.782328 0.83534</point1>
			<point2>-0.396199 0.782328 0.83534</point2>
			<point3>-0.396199 0.782328 0.69128</point3>
		</face>
		<face side="back">
			<point0>-1.19107 0.772328 0.68128</point0>
			<point1>-1.19107 0.772328 0.82534</point1>
			<point2>-0.406199 0.772328 0.82534</point2>
			<point3>-0.406199 0.772328 0.68128</point3>
		</face>
		<handles>17006 </handles>
		<knobs></knobs>
	</candidate>

	<handle name="handle17011" id="17011">
		<center>0.28611 0.0330214 0.09</center>
		<elongation>0.179062 0.00896072 0.00692618</elongation>
		<doorID>25010</doorID>
	</handle>

	<candidate name="cupboard10" id="25010" type="25000" typename="cupboard">
		<wallID>-1</wallID>
		<face side="front">
			<point0>-0.0565787 0.574795 0.74</point0>
			<point1>-0.0565787 0.574795 0.85</point1>
			<point2>0.517622 0.574795 0.85</point2>
			<point3>0.517622 0.574795 0.74</point3>
		</face>
		<face side="back">
			<point0>-0.0565787 0.564795 0.74</point0>
			<point1>-0.0565787 0.564795 0.85</point1>
			<point2>0.517622 0.564795 0.85</point2>
			<point3>0.517622 0.564795 0.74</point3>
		</face>
		<handles>17011 </handles>
		<knobs></knobs>
	</candidate>

	<handle name="handle17010" id="17010">
		<center>0.55 0.0330214 0.5</center>
		<elongation>0.009062 0.00896072 0.15692618</elongation>
		<doorID>25011</doorID>
	</handle>

	<candidate name="cupboard11" id="25011" type="25000" typename="cupboard">
		<wallID>-1</wallID>
		<face side="front">
			<point0>-3.00753 0.574538 0.5</point0>
			<point1>-3.00753 0.574538 1.48</point1>
			<point2>-2.42708 0.574538 1.48</point2>
			<point3>-2.42708 0.574538 0.5</point3>
		</face>
		<face side="back">
			<point0>-3.00753 0.564538 0.5</point0>
			<point1>-3.00753 0.564538 1.48</point1>
